export const actionTypes = {
	SET_TASK: 'SET_TASK',
	DELETE_TASK: 'DELETE_TASK',
	CREATE_TASK: 'CREATE_TASK',
	SET_SELECTED_TASK: 'SET_SELECTED_TASK',
	LOGIN: 'LOGIN',
	SIGNIN: 'SIGNIN',
	LOGOUT: 'LOGOUT',
	MODE: 'MODE',
	ADMIN_ALL_USERS: 'ADMIN_ALL_USERS',
	ADMIN_ALL_TASKS: 'ADMIN_ALL_TASKS'
};
